FROM cnfldemos/cp-server-connect-datagen:0.5.3-7.1.0

# Switch to root user to install packages
USER root

# Installing connector plugins
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.4 && \
    confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:2.5.4 

# Installing Debezium MySQL Connector from tar.gz downloaded manually
RUN curl -L "https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.7.2.Final/debezium-connector-mysql-2.7.2.Final-plugin.tar.gz" -o /tmp/debezium-connector-mysql.tar.gz  && \
    mkdir -p /usr/share/confluent-hub-components/debezium-connector-mysql && \
    tar -xzf /tmp/debezium-connector-mysql.tar.gz -C /usr/share/confluent-hub-components/debezium-connector-mysql && \
    rm -f /tmp/debezium-connector-mysql.tar.gz && \
    curl -L "https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar" -o /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/mysql-connector-j-8.0.33.jar

# Switch back to the non-root user
USER appuser
