FROM confluentinc/cp-server-connect:7.6.0

# Switch to root user to install packages
USER root

# Install Java 17 and Maven using yum
RUN yum update -y && \
    yum install -y java-17-openjdk-devel unzip && \
    yum clean all

# Online Installing connector plugins 
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.8.0 && \
    confluent-hub install --no-prompt confluentinc/kafka-connect-sftp:3.2.14


# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk

# Update PATH
ENV PATH="$JAVA_HOME/bin:${PATH}"

# Switch back to the non-root user
USER appuser

