

mysql> GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'SVC_DS_DEPLOY'@'%';
Query OK, 0 rows affected (0.02 sec)

mysql> GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'SVC_DS_HELPER'@'%';
Query OK, 0 rows affected (0.01 sec)

mysql> GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'SVC_DS_KAFKA'@'%';
Query OK, 0 rows affected (0.01 sec)
